definitions:
  storages.Song:
    properties:
      group:
        type: string
      group_id:
        type: integer
      id:
        type: integer
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@currencywallet.com
    name: API Support
  description: API for searsh songs.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Songs API
  version: "1.0"
paths:
  /songs:
    get:
      description: Получить список песен с пагинацией, отфильтрованный по названию
        группы и песни
      parameters:
      - description: Фильтр по названию группы
        in: query
        name: group
        type: string
      - description: Фильтр по названию песни
        in: query
        name: song
        type: string
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 10
        description: Количество элементов на странице
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storages.Song'
            type: array
        "400":
          description: Неверные параметры запроса
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Не удалось получить песни
          schema:
            additionalProperties: true
            type: object
      summary: Получить список песен
      tags:
      - Песни
    post:
      description: Добавить новую песню в базу данных
      parameters:
      - description: Данные о песне
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/storages.Song'
      responses:
        "201":
          description: Песня добавлена
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверные данные для добавления песни
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Не удалось добавить песню
          schema:
            additionalProperties: true
            type: object
      summary: Добавить новую песню
      tags:
      - Песни
  /songs/{id}/lyrics:
    get:
      description: Получить текст песни с пагинацией для конкретной песни
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 1
        description: Количество элементов на странице
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Неверные параметры запроса
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Не удалось получить текст песни
          schema:
            additionalProperties: true
            type: object
      summary: Получить текст песни
      tags:
      - Тексты песен
  /songs/{id}/partial:
    put:
      description: Обновить одно или несколько свойств песни по ее ID
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      - description: Данные о песне
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/storages.Song'
      responses:
        "200":
          description: Успешно
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверные данные для обновления песни
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Песня не найдена
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Не удалось обновить песню
          schema:
            additionalProperties: true
            type: object
      summary: Частичное обновление информации о песне
      tags:
      - Песни
swagger: "2.0"
